# Generated by Django 3.2.19 on 2023-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('itemsdetail', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=12)),
                ('address', models.TextField(blank=True)),
                ('txref', models.CharField(max_length=25)),
                ('amount', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='fail', max_length=4)),
            ],
        ),
    ]
