# Generated by Django 3.2.19 on 2023-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=100)),
                ('mail', models.EmailField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
